export {default as EditIcon} from './svgs/editicon.svg';
export {default as EmailIcon} from './svgs/emailIcon.svg';
export {default as NotificationIcon} from './svgs/notification.svg';
export {default as CrossRedIcon} from './svgs/crossRed.svg';
export {default as CrossIcon} from './svgs/cross.svg';
export {default as CompanyIcon} from './svgs/company.svg';
export {default as CheckIcon} from './svgs/checkIcon.svg';
export {default as FolderIcon} from './svgs/folderIcon.svg';
export {default as StatusIcon} from './svgs/offlineStatus.svg';
export {default as UploadIcon} from './svgs/Upload.svg';
export {default as CalenderIcon} from './svgs/calender.svg';
export {default as FilterIcon} from './svgs/filter.svg';
export {default as SearchIcon} from './svgs/search.svg';
export {default as LogoName} from '../assets/images/logoBlueName.svg';
export {default as Logo} from '../assets/images/logoImgBlue.svg';
export {default as LeftArrowIcon} from '../assets/images/arrowLeft.svg'
export {default as ShowPasswordIcon} from '../assets/svgs/EyeOpen.svg'
export {default as HidePasswordIcon} from '../assets/svgs/EyeClose.svg'
export {default as PersonIcon} from '../assets/svgs/person-outline.svg'
export {default as PasswordIcon} from '../assets/svgs/pasword.svg'